pid:
  ros__parameters:
    linear_kp: 1.5
    linear_ki: 0.0
    linear_kd: 0.0
    angular_kp: 0.15
    angular_ki: 0.0
    angular_kd: 0.0
    max_linear_velocity: 5.0
    max_angular_velocity: 0.1
    max_accel: 3.0
    arrival_threshold: 0.05
    theta_threshold: 0.01
    kokuban_t : 1000 #ミリ秒
    turn_t : 100
    launcher_1_t : 2000
    ball_t : 1000
    launcher_2_t : 100000
    red_csv: /home/yuki/ros2_ws/src/uni_tes/path/red.csv
    blue_csv: /home/yuki/ros2_ws/src/uni_tes/path/blue.csv
    utikiri: true #目標地点との距離の雑多位置が閾値以下なら強制的に停止するモード
    stop_threshold : 0.05 #↑のモードのときの閾値(m)
